version: "3.9"

services:
  postgres:
    image: postgres:14.1
    container_name: postgresql_prod
    volumes:
      - "postgres:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: default_database      
volumes:
  postgres:
